name: app_config
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  data:
    path: ../data
  flutter:
    sdk: flutter

  # Caching
  hive:
  hive_flutter:
  injectable:
  json_annotation:

dev_dependencies:

  build_runner:
  flutter_test:
    sdk: flutter
  hive_generator:
  injectable_generator:
  json_serializable:
